version: 2
updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore"
    cooldown:
      default-days: 7

  - package-ecosystem: composer
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore"
    cooldown:
      default-days: 7

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore"
    cooldown:
      default-days: 7
